name: Terminal

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  # run on every push on the main branch
  push:
    branches:
    - main

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # with:
        #   lfs: true
      # - name: Set up Python 3.11
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y ffmpeg
          python -m pip install --upgrade pip
          pip install git+https://github.com/x0rzavi/github-readme-terminal.git@main

      - name: Run script
        run: python main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # IMGBB_API_KEY: ${{ secrets.IMGBB_API_KEY }}
          GIFOS_GENERAL_FPS: 13
          GIFOS_GENERAL_LOOP_COUNT: 4

      - name: Push GIF to assets branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: assets
          build_dir: assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
